package com.trade.crosscutting.common.enums;

public enum ErrorEnum {

    INVALID_COUNTERPARTY, INVALID_TYPE, INVALID_DIRECTION, INVALID_LEGAL_ENTITY, INVALID_AMOUNT1, INVALID_AMOUNT2, INVALID_RATE, INVALID_VALUE_DATE, INVALID_STYLE, INVALID_EXPIRY_DATE, INVALID_PREMIUM_DATE, INVALID_CURRENCY, INVALID_CURRENCY_PAIR, INVALID_TRADE_DATE, INVALID_STRATEGY, INVALID_VALUE_DATE_WEEKEND, GENERAL_ERROR
}
